### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by tomitrescak** [davidmarkclements/react-functional#1]
Would you consider updating to react 15?

**Comment by davidmarkclements** [comment]
absolutely - does it not work with 15?

**Comment by tomitrescak** [comment]
It does, but it loads React 0.14.x, effectively increasing the bundle size and duplicating the functionality. All that needs to be changed are the dependencies to ^15.0.0.

**Comment by davidmarkclements** [comment]
I'll take a PR 👍

**Comment by tomitrescak** [comment]
I've done the PR.
