### ISSUE TITLE
Version 3.0.2 not published on npm

### ISSUE THREAD

**Issue by casche** [davidmarkclements/react-functional#9]
Hey @davidmarkclements , after the merging of https://github.com/davidmarkclements/react-functional/pull/8 it doesn't look like 3.0.2 made it to the NPM registry: https://www.npmjs.com/package/react-functional

**Comment by Anenth** [comment]
@davidmarkclements could you publish this?

**Comment by davidmarkclements** [comment]
published - sorry about that

**Comment by Anenth** [comment]
@davidmarkclements no worries, thanks alot
